spring:
  application:
    name: Monitorbot-d4j

bot:
  config:
    token: ${DISCORD_TOKEN}
    report-channel: ${REPORT_CHANNEL_ID}
    thread-rep-threshold: 200
    post-rep-threshold: 50
    schedule-delay: 600000

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${PORT:8080}
